name: Release Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions: write-all
jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: get version information
        run: |
          echo ${{ github.event.pull_request.title }}
          echo "##[set-output name=version;]$(echo '${{ github.event.pull_request.title }}' | egrep -o 'Release/([^[:space:]]+)' | sed 's/Release\///')"
          echo ${{ steps.extract_version_name.outputs.version }}
        id: extract_version_name
      - name: Create Release Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version_name.outputs.version }}
          release_name: v${{ steps.extract_version_name.outputs.version }}
