name: Release Tag
on:
  workflow_run:
    workflows: ["Pull-Request-Merged-To-Main"]
    types:
      - completed
    branches:
      - main
      - dev
jobs:
  on_merge:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v2
      - name: 버전 정보 추출
        run: |
          echo ${{ github.event.pull_request.title }}  
          echo ${{ github.event.head_commit.message }} 
          echo "##[set-output name=version;]$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
          echo ${{ steps.extract_version_name.outputs.version }}
        id: extract_version_name
      - name: Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
          release_name: ${{ steps.extract_version_name.outputs.version }}
